name: Packer Testing
on: [push]
jobs:
  Packer-Fmt-Validate:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Testing my Packer Build"

        - name: AWS authentication
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::342623272824:role/github-oidc
            aws-region: us-east-2
            role-session-name: GithubDeployment

        - name: Checkout
          uses: actions/checkout@v3

        - name: Use latest Packer
          uses: hashicorp-contrib/setup-packer@v1

        - name: Packer Init
          run: packer init

        - name: Packer Format
          run: packer fmt -check

        - name: Packer Validate
          run: packer validate