name: Packer Testing
on: [push]
jobs:
  Packer-Fmt-Validate:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Testing our first workflow"

        - name: Checkout
          uses: actions/checkout@v3

        - name: Use latest Packer
          uses: hashicorp-contrib/setup-packer@v1

        - name: Packer Init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          run: packer init

        - name: Packer Format
          run: packer fmt -check

        - name: Packer Validate
          run: packer validate